base-notebook/cpu/Dockerfile
base-notebook/gpu/Dockerfile

Built this on the cpu base image. My computer will probably crash if I try to compile the GPU Image but I'm assuming that it'll play nice. **I haven't successfully connected via python!** The following should test connectivity
```
from getpass import getpass
import pyodbc
host = 'dremio.covid.cloud.statcan.ca'
port = 31010
driver = '/opt/dremio-odbc/lib64/libdrillodbc_sb64.so'
cnxn = pyodbc.connect(';'.join([
f"Driver={driver}", 
"ConnectionType=Direct;",
f"HOST={host}",
f"PORT={port}",
"AuthenticationType=Plain",
"UID={}".format(getpass('Dremio Username: ')),
"PWD={}".format(getpass('Dremio Password: '))]),
autocommit=True
)
```
However from my machine **this command hangs**. It might be different if run inside the cluster?

Add Dremio. Fixes #13

---

base-notebook/cpu/start-custom.sh
base-notebook/gpu/start-custom.sh

Closes #31 . This --allow-root option seems unnecessary, as we don't
run as root, and the option only seems to be suggested for the that
case.
See https://github.com/kubeflow/kubeflow/issues/300 too.

fix: remove --allow-root option

---

.github/workflows/publish.yml

Would be great to be able to test builds inside of Github. (Some of these images are so large they occasionally crash my personal computer).
This PR moves the old `build.yml` to `publish.yml` (since it builds and pushes) and created a new `build.yml` which *just* builds. (This is consistent with [daaas-containers](https://github.com/StatCan/daaas-containers) )
**Note: The images built in the PR v.s. on master will not be identical because on master, parent images will be mutated by the build process, and in PRs they will not**.
However, I think there are still merits to having *some* build process CI, even if there is a limitation here in terms of not capturing inter-image software changes.

feat(ci/cd): add a build (no push) step to PRs

---

.github/workflows/build.yml

I think this PR (#64 ) Is failing because the image gets pruned before it can be scanned. This isn't a problem in the publish image because it can grab the image from the registry, but it's an issue for `build.yml`
@sylus fixed this in daaas-containers a few days ago, and basically just copying the fix from there
https://github.com/StatCan/daaas-containers/blob/master/.github/workflows/build.yml
Just needed to switch the prune command around.

fix(build.yml): move the docker prune till after scanning

---

base-notebook/cpu/Dockerfile
r-studio/Dockerfile

Error with libssl seems to be a new one. For now just pinning to an older version (like 2 weeks old) and can investigate further from there.
Pinned the base/cpu image while I was at it.

fix(r-studio): fix libssl error in new version (rollback)

---

minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/39
Enabled the extension to display cell execution information in `minimal-notebook-cpu` and `minimal-notebook-gpu`. Also noticed that there was an attempt to use the solarized dark theme in the dockerfiles for the notebooks but it wasn't being implemented correctly so I corrected that too.
I tried to do these changes by using the other `overrides.json` method as explained in [the developer guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#storing-extension-data) but that wasn't working so I did it in the other method using `@jupyterlab/notebook-extension/tracker.jupyterlab-settings`.

feat(notebooks): cell execution information

---

minimal-notebook/cpu/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/39
Changes made to configure user settings through `override.json` instead of `/home/$NB_USER/.jupyter/lab/user-settings/@jupyterlab/` in an attempt to also have the changes be applied when a server is created with a _new_ workspace volume mounted to the notebook.

feat(notebook): execution time and theme changes for persistent storage

---

minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/93
Pinned v0.20.0 to the JupyterLab git server and lab extensions in `minimal-notebook-cpu` and `minimal-notebook-gpu`.

Pin Git Extension Versions (v0.20.0)

---

minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile

Resolves #127 
Jupyterlab-dash is no longer maintained
Needs jupyter-server-proxy.
- Returns connection refused without it

update: jupyterlab-dash to jupyter-dash

---

machine-learning-notebook/cpu/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/138
- Updated tensorflow to version 2.3.1
- Latest version of tensorflow using `conda install` is 2.2.0, so switched to `pip` to get latest version (2.3.1)

chore: update tensorflow version

---

.github/workflows/build.yaml
.github/workflows/push.yaml

This fixes the `context deadline exceeded` issue by pushing to a local registry and scanning from there.
You can see the results here: https://github.com/StatCan/kubeflow-containers/actions/runs/390502488

fix(ci): push to a localhost cr to scan

---

.github/workflows/build.yaml
.github/workflows/push.yaml
output/RStudio/start-custom.sh

This adds a step in the workflow to check that `output` is in-sync with `make all`. (I.e. make sure that no one edited output directly)
Commit 3f515aa shows that it works.
**NOTE: This should be squash-merged**

Test output synced

---

docker-bits/6_RStudio.Dockerfile
output/JupyterLab-CPU/start-custom.sh
output/JupyterLab-PyTorch/start-custom.sh
output/JupyterLab-Tensorflow/start-custom.sh
output/RStudio/Dockerfile
output/RStudio/start-custom.sh
resources/start-custom.sh

This was more complicated than expected! It also adds a [fork of rsession-proxy](https://github.com/blairdrummond/jupyter-rsession-proxy)
First error encountered was a sqlite error not being able to write to a database. The issue seems to have been a simple ownership issue. `/var/lib/rstudio-server/rstudio.sqlite` is owned by `rstudio-server`, but when we start rstudio via jupyter, the running user is `jovyan`. So needed to add:
```
chown $NB_USER:users /var/lib/rstudio-server/rstudio.sqlite
```
And *also* need rserver to use the jovyan user, which leads to [this proxy change](https://github.com/blairdrummond/jupyter-rsession-proxy/blob/eb5c4b7023f82ab7841d55fef54c56ebe7a51705/jupyter_rsession_proxy/__init__.py#L38).
This is just a new setting introduced by [this …

feat(rstudio): upgrade rstudio to 1.4

---

.github/workflows/build.yaml
.github/workflows/push.yaml

pytorch scan timed out (took longer than 2 min).  Extending timeout to fix

fix: Extend timeout for Trivy in build.yaml

---

output/JupyterLab-CPU-OL-compliant/helpers.sh
output/JupyterLab-CPU-OL-compliant/start-custom.sh
output/JupyterLab-CPU/start-custom.sh
output/JupyterLab-PyTorch-OL-compliant/helpers.sh
output/JupyterLab-PyTorch-OL-compliant/start-custom.sh
output/JupyterLab-PyTorch/start-custom.sh
output/JupyterLab-Tensorflow-OL-compliant/helpers.sh
output/JupyterLab-Tensorflow-OL-compliant/start-custom.sh
output/JupyterLab-Tensorflow/start-custom.sh
output/RStudio/start-custom.sh
resources/start-custom.sh

Adds a new flag
https://github.com/jupyter/notebook/commit/c0ab18a53472372e31dee293fefd66f218107c98
Which would otherwise prevent us from scraping `/metrics`.
(We currently can scrape metrics, but this will break once we upgrade to the newer docker-stacks base images.)

feat: add newly introduced prometheus no-auth flag

---

.github/workflows/push_on_comment.yaml
README.md

Adds a "/deploy" keyword to our PRs.  If a repo owner or collaborator comments on a PR with "/deploy", CI will trigger a build+push step for this branch.  Images will be pushed to the main ACR under tags of `:SHA` and `:BRANCH`, and can then be accessed as custom images.  
To prove this works completely, it needs to be merged into master (github actions triggering on comments must be in master branch).  I've debugged in another repo but just in case, to start this does not replace `push.yaml` but instead is a secondary workflow that applies only to JupyterLab-CPU.  If it proves to work well, we can replace `push.yaml` and use this for all push events.  
Will squash on merge to remove the junk commits.

Add deploy triggers

---

.github/workflows/build.yaml

Build (without pushing) every night at 2:am, to make sure everything is happy and healthy

chore(ci): add nightly testing build

---

docker-bits/6_jupyterlab-ol-compliant.Dockerfile
output/jupyterlab-cpu-ol-compliant/Dockerfile
output/jupyterlab-pytorch-ol-compliant/Dockerfile
output/jupyterlab-tensorflow-ol-compliant/Dockerfile

using commit SHA for git extensions until new package release including i18n changes
using forked repo for jupyterlab-lsp that contains i18n until PR is merged in upstream repo

include jupyterlab-git and jupyterlab-lsp localized extensions

---

output/remote-desktop/start-remote-desktop.sh
resources/remote-desktop/start-remote-desktop.sh

Good catch. I never use the doc anymore so didn't notice :( 
Closes #265

fix: use xdg-settings to make firefox default

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile

Using a forked repo release where it is removed.
2/2 Closes https://github.com/StatCan/daaas/issues/568
Changes the code-server we are using for 3.10.2 and a release where the Download Command was removed from the palette.

feat: Block Download from palette vscode

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
resources/common/start-custom.sh

closes #272 
Adds kubernetes environment variables to Renviron file (stores all env var)

add kubectl env var

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
resources/common/start-custom.sh

use full path to jupyter server
Closes https://github.com/StatCan/daaas/issues/805
Have to wait for CVE fix 

fix(jupyter): use full path

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/remote-desktop/start-remote-desktop.sh
output/rstudio/start-custom.sh
resources/common/start-custom.sh
resources/remote-desktop/start-remote-desktop.sh

Resolves the issue where a French nb server
gets restarted and they cannot do anything
Closes https://github.com/StatCan/daaas/issues/866

fix(overwrite): do not append in language file

---

docker-bits/∞_CMD.Dockerfile
output/docker-stacks-datascience-notebook/Dockerfile
output/docker-stacks-datascience-notebook/Rprofile.site
output/docker-stacks-datascience-notebook/pip.conf
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/Rprofile.site
output/jupyterlab-cpu/pip.conf
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/Rprofile.site
output/jupyterlab-pytorch/pip.conf
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/Rprofile.site
output/jupyterlab-tensorflow/pip.conf
output/remote-desktop/.condarc
output/remote-desktop/Rprofile.site
output/remote-desktop/pip.conf
output/rstudio/Dockerfile
output/rstudio/Rprofile.site
output/rstudio/pip.conf
resources/common/Rprofile.site
resources/common/pip.conf
resources/remote-desktop/.condarc

I've changed the URL `http://jfrog-platform-artifactory-ha.jfrog-system:8081` to `https://jfrog.aaw.cloud.statcan.ca/` everywhere. Fixes StatCan/daaas#840.
I tested this by manually changing the URLs inside a running container on the AAW and this allowed me to install any package, including `opencv`.

fix(StatCan/daaas#840): difficulty installing from conda

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile

Related upstream issue: https://github.com/aws/aws-sam-cli/issues/3661

fix(jupyter-images)Downgrade markupsafe to v2.0.1

---

docker-bits/∞_CMD.Dockerfile
output/docker-stacks-datascience-notebook/Dockerfile
output/docker-stacks-datascience-notebook/Rprofile.site
output/docker-stacks-datascience-notebook/pip.conf
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/Rprofile.site
output/jupyterlab-cpu/pip.conf
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/Rprofile.site
output/jupyterlab-pytorch/pip.conf
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/Rprofile.site
output/jupyterlab-tensorflow/pip.conf
output/remote-desktop/.condarc
output/remote-desktop/Rprofile.site
output/remote-desktop/pip.conf
output/rstudio/Dockerfile
output/rstudio/Rprofile.site
output/rstudio/pip.conf
output/sas/Dockerfile
output/sas/Rprofile.site
output/sas/pip.conf
resources/common/Rprofile.site
resources/common/pip.conf
resources/remote-desktop/.condarc

Closes #332 this should fix prod and protected b notebooks
needing to specify the url to install packages

fix(jfrog url): use internal urls

---

docker-bits/4_CLI.Dockerfile
docker-bits/∞_CMD.Dockerfile
output/docker-stacks-datascience-notebook/Dockerfile
output/docker-stacks-datascience-notebook/trino-wrapper.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/trino-wrapper.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/trino-wrapper.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/trino-wrapper.sh
output/remote-desktop/Dockerfile
output/remote-desktop/trino-wrapper.sh
output/rstudio/Dockerfile
output/rstudio/trino-wrapper.sh
output/sas/Dockerfile
output/sas/trino-wrapper.sh
resources/common/trino-wrapper.sh

closes https://github.com/StatCan/daaas/issues/930

add: trino wrapper script

---

docker-bits/6_remote-desktop.Dockerfile
output/remote-desktop/Dockerfile
output/remote-desktop/desktop-files/openmpp.desktop
resources/remote-desktop/desktop-files/openmpp.desktop

Add super for multiple user managed OpenM++ versions to be installed side by side and enable testing of model development and results.
Closes #353 

Update OpenM++ installation to support multiple simultaneous versions

---

.github/containerscan/allowedlist.yaml

See comment on https://github.com/StatCan/daaas-private/issues/16
Closes StatCan/daaas-private#16

chore(allowedlist): include CVE-2022-34749 to whitelist

---

output/docker-stacks-datascience-notebook/shell_helpers.sh
output/jupyterlab-cpu/shell_helpers.sh
output/jupyterlab-pytorch/shell_helpers.sh
output/jupyterlab-tensorflow/shell_helpers.sh
output/remote-desktop/shell_helpers.sh
output/rstudio/shell_helpers.sh
output/sas/shell_helpers.sh
resources/common/shell_helpers.sh

Closes https://github.com/StatCan/daaas/issues/1299

fix(trino): add default JNA storage location

---

docker-bits/3_Kubeflow.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

CVE in pypi package joblib used by sklearn and the base docker image. Installed joblib version 1.2.0 to resolve CVE

fix(cve):CVE-2022-21797

---

docker-bits/6_jupyterlab.Dockerfile
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/Dockerfile
output/sas/start-custom.sh
resources/common/start-custom.sh

fix: persist code-server settings and extensions

---

docker-bits/6_sas.Dockerfile
output/sas/Dockerfile
output/sas/spawner_usermods.sh
resources/sas/spawner_usermods.sh

closes https://github.com/StatCan/daaas/issues/1402

add: enable xcmd option in sas studio

---

docker-bits/6_jupyterlab.Dockerfile
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/Dockerfile
output/sas/start-custom.sh
resources/common/start-custom.sh

Modifying the persisted directory for vscode settings to see if it fixes clients crashloopbackoff issues

update: vscode settings.json path

---

docker-bits/0_cpu.Dockerfile
output/jupyterlab-cpu/.condarc
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/.condarc
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/.condarc
output/jupyterlab-tensorflow/Dockerfile
output/rstudio/.condarc
output/rstudio/Dockerfile
output/sas/.condarc
output/sas/Dockerfile
resources/common/.condarc

This resource specifies the location for conda envs to be created in $HOME/.conda/envs. Note: This does not affect the /opt/conda default envs location and the initial base env. Future environments are then stored in the specified condarc file. Reasoning:
Conda environments stored in the default /opt/conda are ephimeral. By selecting a location under $HOME we make sure that the pod configurations and environments are stored in a permanent volume.

Conda envs pointing to location inside the home folder (permanent conda environments)

---

.github/workflows/build_push.yaml
docker-bits/2_pytorch.Dockerfile
output/jupyterlab-pytorch/Dockerfile

Closes https://github.com/StatCan/daaas-private/issues/43

updated pytorch versions to fix cve

---

docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_sas.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

Replaces the R extension since with the official one at https://open-vsx.org/extension/REditorSupport/r

fix(code-server): replace R extension

---

docker-bits/∞_CMD.Dockerfile
docker-bits/∞_CMD_remote-desktop.Dockerfile
output/docker-stacks-datascience-notebook/Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Addresses part of https://github.com/StatCan/daaas/issues/1362

config(pip): change global timeout to 300s

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

closes https://github.com/StatCan/aaw-kubeflow-containers/issues/449
tested with k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:5fcd3aa923e830a7df61ee7550112cdbbe1f5c0b

updated jupyter language pack

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

Changes the default editor to `nano`
Closes https://github.com/StatCan/aaw-kubeflow-containers/issues/331
Processes which open an editor default to nano, example `git commit`:
**Test image** : `k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:434be744038c04795557abec0999075ab6038947`

feat(Editor): change default to nano

---

.github/workflows/build_push.yaml

Added slack notification for the 2 declared jobs. It will send a slack notification only if the schedule event (night build) fails (aka a failure occurs in declared jobs).
closes https://github.com/StatCan/aaw-kubeflow-containers/issues/326

Add slack notifications for nightly build

---

docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Adds the argo cli for ease of use
dev image for testing: k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:df70eff1 
closes #466

feat(argo-cli) add argo cli to all notebooks

---

output/docker-stacks-datascience-notebook/aaw-suspend-server.sh
output/jupyterlab-cpu/aaw-suspend-server.sh
output/jupyterlab-pytorch/aaw-suspend-server.sh
output/jupyterlab-tensorflow/aaw-suspend-server.sh
output/remote-desktop/aaw-suspend-server.sh
output/rstudio/aaw-suspend-server.sh
output/sas/aaw-suspend-server.sh
resources/common/aaw-suspend-server.sh
scripts/aaw-suspend-server.sh

Closes https://github.com/StatCan/aaw-kubeflow-containers/issues/478
Removes an extra suspend script that I think we added by accident in https://github.com/StatCan/aaw-kubeflow-containers/pull/467/files, it was not used in that pr, nor is it used in the docker-bits

chore(sus script): fix shebang add argument

---

.github/workflows/build_push.yaml
Makefile
make_helpers/get_branch_name.sh

update workflow to use $GITHUB_OUTPUT instead of set-output.
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Update build_push.yaml: deprecate set-output

---

Makefile

@vexingly discovered the version of Docker that Github Actions uses was updated right before our builds started failing.
For the successful builds before August 04th 2023, we have the following image version:
```
Runner Image
Image: ubuntu-22.04
Version: 20230724.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230724.1/images/linux/Ubuntu2204-Readme.md
```
And when the builds started failing, we have a new version of the runner (still based on Ubuntu 22.04):
```
Image: ubuntu-22.04
Version: 20230728.3.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230728.3/images/linux/Ubuntu2204-Readme.md
```
For the older, successful runs:
```
Checking docker version
/usr/bin/docker version --format '{{.Server.APIVersion}}'
'1.41'
Docker …
```

Update Makefile: add DOCKER_BUILDKIT=0 to docker build

---

Makefile

Previously I [deprecated set-output for the Github Actions](https://github.com/StatCan/aaw-kubeflow-containers/pull/491), this PR is for deprecating set-output in the Makefile.

update set-output to GITHUB_OUTPUT

---

output/docker-stacks-datascience-notebook/shell_helpers.sh
output/jupyterlab-cpu/shell_helpers.sh
output/jupyterlab-pytorch/shell_helpers.sh
output/jupyterlab-tensorflow/shell_helpers.sh
output/remote-desktop/shell_helpers.sh
output/rstudio/shell_helpers.sh
output/sas/shell_helpers.sh
resources/common/shell_helpers.sh

Closes https://github.com/StatCan/aaw-kubeflow-containers/issues/489

chore(shell helper): update minio to "buckets"

---

.github/containerscan/allowedlist.yaml
.github/workflows/build_push.yaml

Just makes the allowlist secret. Note that the previous CVEs on the allowlist seem to not be getting triggered anymore (probably updates / re-assesing of vulnerability).
The one thing I am unsure about is if the secret has to be made in the repo but we will find out via the workflow.
If it does need to be created it can just be an empty value.
No `auto-deploy` tag needed as we are not making any changes to the dockerfiles, just to the workflow.
Related to: https://github.com/StatCan/aaw-private/issues/123

chore(allowlist): secretify it

---

docker-bits/6_sas.Dockerfile
output/sas/Dockerfile

This is to update SASPy from 4.1.0 to 5.4.0 for compatibility with Python 3.11.
/closes https://github.com/StatCan/aaw-kubeflow-containers/issues/537

update(saspy): SASPy 4.1.0 -> 5.4.0

---

.github/workflows/build_push.yaml
output/jupyterlab-cpu/.Rprofile
output/jupyterlab-pytorch/.Rprofile
output/jupyterlab-tensorflow/.Rprofile
output/remote-desktop/.Rprofile
output/rstudio/.Rprofile
output/sas/.Rprofile
resources/common/.Rprofile

@vexingly discovered `options(download.file.method="wget")` which can be added to `.Rprofile` which seems to fix the issue. As of this writing I am still unaware of what is causing the issue but this workaround fixes things for now.
- https://stackoverflow.com/questions/70559397/r-internet-routines-cannot-be-loaded-when-starting-from-rstudio
After adding `options(download.file.method="wget")` to `.Rprofile` I am once again able to install packages using RStudio.

Set wget as the default package downloader for RStudio.

---

output/docker-stacks-datascience-notebook/start-oms.sh
output/jupyterlab-cpu/start-oms.sh
output/jupyterlab-pytorch/start-oms.sh
output/jupyterlab-tensorflow/start-oms.sh
output/remote-desktop/start-oms.sh
output/rstudio/start-oms.sh
output/sas/start-oms.sh
resources/common/start-oms.sh

No longer copying the sample models from the OMPP release to the buckets, this should also speed up the `start-oms.sh` script. If needed, those sample models can still be copied over manually.

Ompp cleanup models

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

Fixes https://github.com/StatCan/aaw/issues/1945
No but that is from master and is a known thing
TESTED ON k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:c56b5330f02d78387fa8af68d227e47800e20bb8

added pexpect tagged version to fix git push bug

---

.github/scripts/cleanup_runner.sh

fixes https://github.com/StatCan/aaw-private/issues/171
code should only impact the github workflow, not the images
tested k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:b6086de96e91141dd22d06f951e70a6d5c1709b5

Sas image - no space left issue

---

docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_rstudio.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Fixes https://github.com/StatCan/aaw-private/issues/178
TESTED WITH k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:10d4b1e7

updated jupyer-server-proxy package

---

docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_remote-desktop.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/remote-desktop/desktop-files/openmpp.desktop
output/sas/Dockerfile
resources/remote-desktop/desktop-files/openmpp.desktop

Updated OpenM to version 1.16.0

chore(openmpp): bump to 1.16.1

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

For some reason this updated or something...
as I cannot install say `pandas` naturally.
`pip install pandas` will just fail on das. whereas `pip install pandas --extra-index-url` with the above url with `/simple` works

chore(pypi): fix repo

---

docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

These dev packages are required by some important R packages:
More info can be found here:
- https://jirab.statcan.ca/browse/BTIS-235

Add font dev packages for r dependencies

---

.github/workflows/build_push.yaml

fix(CI): removed test image step from workflow

---

.github/workflows/build_push.yaml
Makefile
requirements-dev.txt
tests/general/test_packages.py

fix(Test Images): pinned requests package

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile
tests/general/test_packages.py

This was necessary to actually fix https://jirab.statcan.ca/browse/BTIS-235.
R seems to require that we have pkg-config installed by mamba/conda.
- https://stackoverflow.com/questions/68824450/error-configuration-failed-for-package-ragg

Add pkg config to conda

---

Makefile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile

adding rstudio to jupyterlab just like in the sas image
ticket: https://jirab.statcan.ca/browse/BTIS-377

add rstudio to jupyterlab image

---

.github/workflows/build_push.yaml

https://jirab.statcan.ca/browse/BTIS-421

removed tensorflow from build

---

.github/workflows/build_push.yaml

https://jirab.statcan.ca/browse/BTIS-421

removed tensorflow and pytorch images from git workflow builds

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

Ticket: https://jirab.statcan.ca/browse/ZPS-63

Fix python path in vscode

---

.github/workflows/build_push.yaml
docker-bits/0_Rocker.Dockerfile
docker-bits/4_CLI.Dockerfile
docker-bits/6_remote-desktop.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Fix(Remote Desktop): repair quarto, vscode extensions

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

Replaces rpug-conda with the remote channels since it seems to fix https://jirab.statcan.ca/browse/BTIS-490

fix(conda): remove rpug channel

---

.gitignore
Makefile
docker-bits/0_Rocker.Dockerfile
output/remote-desktop/Dockerfile

Fixes the issue addressed in: 
https://github.com/StatCan/aaw-kubeflow-containers/issues/663
includes an edit to the make file, as the variable GITHUB_OUTPUT is undefined, and made me unable to build.

Fix to remote-desktop

---

.github/workflows/build_push.yaml
docker-bits/∞_CMD.Dockerfile
output/docker-stacks-datascience-notebook/Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Test if changing ownership of user's home directory from root to user fixes byobu startup error.

---

.github/workflows/build_push.yaml

Changed trivy error code to 10. This means if vulnerabilities are found, it will error with exit code 10. 
This lets us retry any scan that had an error that was not finding vulnerabilities, since general errors are code 1. 
Will retry up to 5 times. 
The code is written like this as trivy doesn't actually write anything to an output variable on return, so there isn't any way to look for the `TOOMANYREQUESTS` error specifically. 
Closes https://github.com/StatCan/aaw/issues/1981

Add retry functionality to Trivy scan

---

docker-bits/6_sas.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

Add `lmodern` so Quarto can produce PDF documents.
- JIRA: https://jirab.statcan.ca/browse/BTIS-592
The issue was resolved by installing the `lmodern` package using `apt-get`. However, it was necessary to run `apt-get update` beforehand, as the SAS image was unable to locate the `lmodern` package without updating the package lists.

Add lmodern so Quarto can produce PDF documents.

---

docker-bits/4_CLI.Dockerfile
output/docker-stacks-datascience-notebook/ktutil-keytab.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/ktutil-keytab.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/ktutil-keytab.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/ktutil-keytab.sh
output/remote-desktop/Dockerfile
output/remote-desktop/ktutil-keytab.sh
output/rstudio/Dockerfile
output/rstudio/ktutil-keytab.sh
output/sas/Dockerfile
output/sas/ktutil-keytab.sh
resources/common/ktutil-keytab.sh

for https://jirab.statcan.ca/browse/BTIS-700 
Can be tested by running "ktutil-keytab" in a terminal in a running notebook

feat: add ktutil and a helper script to our images

---

.github/workflows/docker-nightly.yaml

Late in Dev I changed the registry to be the whole url `k8scc01covidacr.azurecr.io` instead of just being the one part `k8scc01covidacr`.
This wasn't changed in `docker-nightly.yaml`, so the builds failed last night.

fix nightly

---

.github/workflows/docker-build-upload.yaml
images/base/Dockerfile
images/cmd/Dockerfile
images/platform/Dockerfile
images/pytorch/Dockerfile
images/remote-desktop/Dockerfile
images/rstudio/Dockerfile
images/sas/Dockerfile
images/tensorflow/Dockerfile

investigates removing `--no-fail` from Hadolint
Part of https://github.com/StatCan/aaw-kubeflow-containers/issues/732
Hadolint checks had to be moved below the `FROM *** as ***` injection, or would else error out on the missing `FROM`
Fixes made for
- fixes https://github.com/hadolint/hadolint/wiki/DL3003 (Use absolute paths, or use WORKDIR to switch to a directory)
- fixes https://github.com/hadolint/hadolint/wiki/DL3004 (Do not use sudo)
- fixes https://github.com/hadolint/hadolint/wiki/DL3005 (Do not use apt-get dist-upgrade)
- fixes https://github.com/hadolint/hadolint/wiki/DL3027 (Do not use apt, it is an end-user tool, use apt-get instead)
- fixes https://github.com/hadolint/hadolint/wiki/DL3042 (Avoid cache directory with pip install --no-cache-dir)
- fixes …

Enable Hadolint to fail builds

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

With the curl command, it would still copy the output of the curl to the output file, even on an error. We dont want that as it overrites the file, which we only want to do on success. Switched to a git clone command like how our example notebooks get done.

fix: tnsnames.ora clone script fix

---

images/base/Dockerfile
images/remote-desktop/Dockerfile
images/remote-desktop/desktop-files/openmpp.desktop

Fix issue in https://github.com/StatCan/aaw/issues/2016
The newer version of OpenM++ need `glibc v2.38`, but on our current version we have `glibc v2.35`
This version is set by the Ubuntu version, which is set by our base image. 
We can upgrade OpenM++ once https://github.com/StatCan/aaw/issues/2014 is finished.

roll back OpenM++ version
