minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile

Added a couple R packages, pyarrow (closes #14), pachctl, and also installed golang.
@zachomedia  if you could take a look at the golang configuration and make suggestions that would be good. I'm a golang noob; hope that $GOPATH and $GOROOT are configured sensibly here.

jupyterlab update & golang & pachctl

---

minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile

Just switching this back to stable since Elyra now supports the newer jupyterlab and doesn't need my fork anymore.
Also enabled the the extension the code snippets package.

feat(elyra): Back to stable

---

.checksum-checks/CHECKSUMS
.checksum-checks/checksums.sh
minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile
r-studio/Dockerfile

Minio moved old releases to a folder; had to fix the wget url.

fix(minio): fix url; mc moves releases to an archive

---

minimal-notebook/gpu/Dockerfile

Added the theme and cell execution information changes to the `minimal-notebook-gpu` as well.

feat(notebook): theme and cell execution for GPU

---

r-studio/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/110

fix: remove duplicates

---

r-studio/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/123

fix: update ubuntu version

---

.checksum-checks/CHECKSUMS
.checksum-checks/checksums.sh
minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile

WIP - Do not merge, still need to test building minimal notebook

refactor: remove go kernel from jupyterlab images

---

base-notebook/gpu/Dockerfile
geomatics-notebook/cpu/Dockerfile
machine-learning-notebook/cpu/Dockerfile
machine-learning-notebook/gpu/Dockerfile
minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile
r-studio/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/106

fix: pin versions for cpu and gpu packages

---

minimal-notebook/cpu/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/109

fix: update lsp extension version

---

base-notebook/cpu/Dockerfile
geomatics-notebook/cpu/Dockerfile
machine-learning-notebook/cpu/Dockerfile
minimal-notebook/cpu/Dockerfile
r-studio/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/117 and https://github.com/StatCan/kubeflow-containers/issues/130
* updated jupyter/datascience-notebook image version (python 3.8.5)
* updated package versions
* installed pytorch/torch using pip instead of conda
* removed double package installations

feat: updated inherited image for cpu images

---

base-notebook/cpu/Dockerfile
base-notebook/gpu/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/131

fix: update tekton version

---

base-notebook/cpu/Dockerfile
base-notebook/gpu/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/131

fix: update kpf-tekton version

---

minimal-notebook/cpu/Dockerfile
minimal-notebook/gpu/Dockerfile

Resolves: https://github.com/StatCan/kubeflow-containers/issues/141

fix: change default theme from solarized to dark

---

docker-bits/6_RStudio.Dockerfile
output/RStudio/Dockerfile

fix: ubuntu version update

---

docker-bits/2_PyTorch.Dockerfile
docker-bits/2_Tensorflow.Dockerfile
docker-bits/6_JupyterLab.Dockerfile
docker-bits/6_RStudio.Dockerfile
output/JupyterLab-CPU/Dockerfile
output/JupyterLab-PyTorch/Dockerfile
output/JupyterLab-Tensorflow/Dockerfile
output/RStudio/Dockerfile

Resolves https://github.com/StatCan/kubeflow-containers/issues/106

chore: pin extension and package versions

---

docker-bits/2_PyTorch.Dockerfile
output/JupyterLab-PyTorch/Dockerfile

fix: Pin an older version of pytorch/accessories to fix build

---

output/JupyterLab-CPU/start-custom.sh
output/JupyterLab-PyTorch/start-custom.sh
output/JupyterLab-Tensorflow/start-custom.sh
output/RStudio/start-custom.sh
resources/start-custom.sh

Resolves https://github.com/StatCan/kubeflow-containers/issues/149
Corrected comparison statement
Used export for the env variable

feat: export LANG based on KF_LANG

---

docker-bits/6_JupyterLab.Dockerfile
output/JupyterLab-CPU/Dockerfile
output/JupyterLab-CPU/start-custom.sh
output/JupyterLab-PyTorch/Dockerfile
output/JupyterLab-PyTorch/start-custom.sh
output/JupyterLab-Tensorflow/Dockerfile
output/JupyterLab-Tensorflow/start-custom.sh
output/RStudio/start-custom.sh
resources/start-custom.sh

I have tested Kale and it works with the v0.6.0 release though there is a customization we need to make it work with multi-user pipelines.
See this issue along with this comment for rationale:
https://github.com/kubeflow-kale/kale/issues/210#issuecomment-727018461

feat(kale): Add kale v0.6.0

---

output/JupyterLab-CPU-OL-compliant/start-custom.sh
output/JupyterLab-CPU/start-custom.sh
output/JupyterLab-PyTorch-OL-compliant/start-custom.sh
output/JupyterLab-PyTorch/start-custom.sh
output/JupyterLab-Tensorflow-OL-compliant/start-custom.sh
output/JupyterLab-Tensorflow/start-custom.sh
output/RStudio/start-custom.sh
resources/start-custom.sh

fix: indentation

---

docker-bits/6_RStudio.Dockerfile
output/JupyterLab-CPU/helpers.sh
output/JupyterLab-PyTorch/helpers.sh
output/JupyterLab-Tensorflow/helpers.sh
output/RStudio/Dockerfile
output/RStudio/helpers.sh
resources/helpers.sh

fixes https://github.com/StatCan/daaas/issues/352
Need to verify it works as expected. 
Might be needed to :
- add `www-allow-origin`
- Remove `www-frame-origin=none` since it is set in the proxy

fix(rstudio): Rstudio hardening

---

docker-bits/6_JupyterLab-OL-compliant.Dockerfile
output/JupyterLab-CPU-OL-compliant/Dockerfile
output/JupyterLab-CPU-OL-compliant/start-custom.sh
output/JupyterLab-CPU/start-custom.sh
output/JupyterLab-PyTorch-OL-compliant/Dockerfile
output/JupyterLab-PyTorch-OL-compliant/start-custom.sh
output/JupyterLab-PyTorch/start-custom.sh
output/JupyterLab-Tensorflow-OL-compliant/Dockerfile
output/JupyterLab-Tensorflow-OL-compliant/start-custom.sh
output/JupyterLab-Tensorflow/start-custom.sh
output/RStudio/start-custom.sh
resources/start-custom.sh

feat(git): add git extension for Jlab 3.0 upgrade

---

docker-bits/6_JupyterLab.Dockerfile
docker-bits/6_RStudio.Dockerfile
output/JupyterLab-CPU/Dockerfile
output/JupyterLab-PyTorch/Dockerfile
output/JupyterLab-Tensorflow/Dockerfile
output/RStudio/Dockerfile

Fix jupyter server

---

Makefile
docker-bits/0_CPU.Dockerfile
docker-bits/6_JupyterLab-OL-compliant.Dockerfile
docker-bits/6_JupyterLab.Dockerfile
docker-bits/6_RStudio.Dockerfile
output/JupyterLab-CPU-OL-compliant/Dockerfile
output/JupyterLab-CPU/Dockerfile
output/JupyterLab-PyTorch-OL-compliant/Dockerfile
output/JupyterLab-PyTorch/Dockerfile
output/JupyterLab-Tensorflow-OL-compliant/Dockerfile
output/JupyterLab-Tensorflow/Dockerfile
output/RStudio/Dockerfile

feat(jupyterlab): bump main images to 3.0

---

tests/jupyterlab-cpu/test_julia.py
tests/jupyterlab-pytorch/test_pytorch.py

add julia and pytorch tests

---

Makefile
README.md
conftest.py
tests/general/test_notebook.py

Suggested edits to test suite to use NB_PREFIX

Suggested edits to test suite to use NB_PREFIX

---

output/remote-desktop/nginx.conf
resources/remote-desktop/nginx.conf

feat: add /proxy for remote-desktop

---

.github/containerscan/allowedlist.yaml

Resolves #167 
Some CVEs have been whitelisted over time (mostly coming from vscode) and need to be looked into - see the ones that still exist and find patched versions of the packages causing these CVEs.

chore: investigate whitelisted CVEs

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/remote-desktop/start-remote-desktop.sh
output/rstudio/start-custom.sh
resources/common/start-custom.sh
resources/remote-desktop/start-remote-desktop.sh

Modify NB_NAMESPACE variable

---

docker-bits/3_Kubeflow.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile

fix: remove vulnerable package

---

output/docker-stacks-datascience-notebook/mc-tenant-wrapper.sh
output/jupyterlab-cpu/mc-tenant-wrapper.sh
output/jupyterlab-pytorch/mc-tenant-wrapper.sh
output/jupyterlab-tensorflow/mc-tenant-wrapper.sh
output/remote-desktop/mc-tenant-wrapper.sh
output/rstudio/mc-tenant-wrapper.sh
resources/common/mc-tenant-wrapper.sh

**fix mc command to handle quotes*

Fix: mc command to handles quotes

---

docker-bits/3_Kubeflow.Dockerfile
docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_rstudio.Dockerfile
docker-bits/7_remove_vulnerabilities.Dockerfile
make_helpers/get_branch_name.sh
output/docker-stacks-datascience-notebook/README.md
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/README.md
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/README.md
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/README.md
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/rstudio/README.md
resources/common/README.md

This P.R. addresses https://github.com/StatCan/daaas/issues/639

feat(repo): Rename github repos and update links

---

docker-bits/0_cpu.Dockerfile
docker-bits/3_Kubeflow.Dockerfile
docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_remote-desktop.Dockerfile
docker-bits/6_rstudio.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
tests/general/test_packages.py

fix: upgrade base images and packages

---

docker-bits/1_CUDA-11.1.Dockerfile
output/jupyterlab-tensorflow/Dockerfile

update tf cuda version

---

docker-bits/2_pytorch.Dockerfile
docker-bits/3_Kubeflow.Dockerfile
docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile

fix(cves): upgrade pillow version

---

.github/workflows/build_push.yaml

Comment out azure container scan in build script.
Upstream issue: https://github.com/Azure/container-scan/issues/122

Comment out azure container scan

---

.github/workflows/build_push.yaml

Reverts StatCan/aaw-kubeflow-containers#318

Revert "Comment out azure container scan"

---

docker-bits/3_Kubeflow.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile

Update kfp and kfp-api version to v1.7.0

fix: update kfp version

---

docker-bits/3_Kubeflow.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile

fix(kfp):update kfp version

---

.github/workflows/build_push.yaml
docker-bits/0_cpu.Dockerfile
docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

closes https://github.com/StatCan/daaas/issues/929

feat: install trino cli

---

docker-bits/∞_CMD.Dockerfile
output/docker-stacks-datascience-notebook/Dockerfile
output/docker-stacks-datascience-notebook/trino-wrapper.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/trino-wrapper.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/trino-wrapper.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/trino-wrapper.sh
output/remote-desktop/trino-wrapper.sh
output/rstudio/Dockerfile
output/rstudio/trino-wrapper.sh
output/sas/Dockerfile
output/sas/trino-wrapper.sh
resources/common/trino-wrapper.sh

chore: update trino wrapper

---

.github/workflows/build_push.yaml

chore(sas): remove sas images temporarily

---

.github/workflows/build_push.yaml
docker-bits/6_sas.Dockerfile
output/sas/Dockerfile

Thanks to efforts of Will can re-enable this.
Closes https://github.com/StatCan/daaas-private/issues/11

chore(sas): re-enable and update the base

---

Makefile
output/sas/Dockerfile

Hopefully this will have everything build

fix(sas-ci): remove extra env installation

---

docker-bits/6_remote-desktop.Dockerfile
output/remote-desktop/Dockerfile
output/remote-desktop/desktop-files/openmpp.desktop
resources/remote-desktop/desktop-files/openmpp.desktop

Port Changes from Fork

---

output/docker-stacks-datascience-notebook/trino-wrapper.sh
output/jupyterlab-cpu/trino-wrapper.sh
output/jupyterlab-pytorch/trino-wrapper.sh
output/jupyterlab-tensorflow/trino-wrapper.sh
output/remote-desktop/trino-wrapper.sh
output/rstudio/trino-wrapper.sh
output/sas/trino-wrapper.sh
resources/common/trino-wrapper.sh

feat: add user flag

---

README.md
output/remote-desktop/README.md
resources/remote-desktop/README.md

Readme update regarding qgis key expiration :)

doc(qgis_key): update key details

---

docker-bits/6_sas.Dockerfile
output/sas/Dockerfile

Fixes https://github.com/StatCan/aaw-kubeflow-containers/issues/383.

fix(SAS): add support for MinIO.

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

add: trino pw envar

---

docker-bits/6_sas.Dockerfile
output/sas/Dockerfile

add: install vscode on sas image

---

docker-bits/6_sas.Dockerfile
output/sas/Dockerfile

code-server

---

docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_sas.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

update: vscode extensions

---

docker-bits/6_sas.Dockerfile
output/sas/Dockerfile

add: install r-studio quarto

---

docker-bits/6_remote-desktop.Dockerfile
output/docker-stacks-datascience-notebook/start-custom.sh
output/docker-stacks-datascience-notebook/trino-wrapper.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-cpu/trino-wrapper.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-pytorch/trino-wrapper.sh
output/jupyterlab-tensorflow/start-custom.sh
output/jupyterlab-tensorflow/trino-wrapper.sh
output/remote-desktop/Dockerfile
output/remote-desktop/start-custom.sh
output/remote-desktop/start-remote-desktop.sh
output/remote-desktop/trino-wrapper.sh
output/rstudio/start-custom.sh
output/rstudio/trino-wrapper.sh
output/sas/start-custom.sh
output/sas/trino-wrapper.sh
resources/common/start-custom.sh
resources/common/trino-wrapper.sh
resources/remote-desktop/start-remote-desktop.sh

feat(jwt): Use JWT in trino-cli

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

remove(temp): vs-code persisted dir logic

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

chore(startup): add trace messages

---

.github/workflows/build_push.yaml
output/docker-stacks-datascience-notebook/pip.conf
output/docker-stacks-datascience-notebook/shell_helpers.sh
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/pip.conf
output/jupyterlab-cpu/shell_helpers.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/pip.conf
output/jupyterlab-pytorch/shell_helpers.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/pip.conf
output/jupyterlab-tensorflow/shell_helpers.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/pip.conf
output/remote-desktop/shell_helpers.sh
output/remote-desktop/start-custom.sh
output/remote-desktop/start-remote-desktop.sh
output/rstudio/pip.conf
output/rstudio/shell_helpers.sh
output/rstudio/start-custom.sh
output/sas/pip.conf
output/sas/shell_helpers.sh
output/sas/start-custom.sh
resources/common/pip.conf
resources/common/shell_helpers.sh
resources/common/start-custom.sh
resources/remote-desktop/start-remote-desktop.sh

Related to https://github.com/StatCan/aaw-kubeflow-containers/issues/417 (force users to create and use a venv)
Add a sleep depending on if an environment variable is present https://github.com/StatCan/aaw-kubeflow-containers/issues/418

add sleep on env, force venv, test

---

output/docker-stacks-datascience-notebook/pip.conf
output/docker-stacks-datascience-notebook/shell_helpers.sh
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/pip.conf
output/jupyterlab-cpu/shell_helpers.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/pip.conf
output/jupyterlab-pytorch/shell_helpers.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/pip.conf
output/jupyterlab-tensorflow/shell_helpers.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/pip.conf
output/remote-desktop/shell_helpers.sh
output/remote-desktop/start-custom.sh
output/remote-desktop/start-remote-desktop.sh
output/rstudio/pip.conf
output/rstudio/shell_helpers.sh
output/rstudio/start-custom.sh
output/sas/pip.conf
output/sas/shell_helpers.sh
output/sas/start-custom.sh
resources/common/pip.conf
resources/common/shell_helpers.sh
resources/common/start-custom.sh
resources/remote-desktop/start-remote-desktop.sh

A clean pr of some changes proposed here https://github.com/StatCan/aaw-kubeflow-containers/pull/421
and handles this https://github.com/StatCan/aaw-kubeflow-containers/pull/356

chore(pyvenv): create and use python venv by default

---

Makefile
docker-bits/6_sas.Dockerfile
output/sas/Dockerfile

Resolves https://github.com/StatCan/daaas/issues/1389

Fix rstudio sas

---

Makefile
docker-bits/6_remote-desktop.Dockerfile
output/docker-stacks-datascience-notebook/Dockerfile
output/remote-desktop/Dockerfile

closes https://github.com/StatCan/daaas/issues/1473

1473 remote desktop add libreoffice writter

---

docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

update: trino-cli version 406

---

docker-bits/6_remote-desktop.Dockerfile
output/remote-desktop/Dockerfile

closes https://github.com/StatCan/daaas/issues/1507

added git-gui

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/remote-desktop/start-remote-desktop.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh
resources/remote-desktop/start-remote-desktop.sh

Closes https://github.com/StatCan/aaw-kubeflow-containers/issues/295

chore: suppress 1337 message and fix other

---

docker-bits/0_cpu.Dockerfile
docker-bits/0_cpu_sas.Dockerfile
docker-bits/6_remote-desktop.Dockerfile
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/Dockerfile
output/remote-desktop/start-custom.sh
output/remote-desktop/start-remote-desktop.sh
output/rstudio/Dockerfile
output/rstudio/start-custom.sh
output/sas/Dockerfile
output/sas/start-custom.sh
resources/common/start-custom.sh
resources/remote-desktop/start-remote-desktop.sh

rebase(main)

---

docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

update: trino-cli v410

---

.github/workflows/build_push.yaml
docker-bits/0_cpu.Dockerfile
docker-bits/0_cpu_sas.Dockerfile
docker-bits/6_remote-desktop.Dockerfile
docker-bits/7_remove_vulnerabilities.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

update references to daaas to aaw

change daaas to aaw

---

docker-bits/6_remote-desktop.Dockerfile
output/remote-desktop/Dockerfile

I have added the full libre office package to our remote desktop image.

update(remote-desktop): full libreoffice

---

docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Closes https://github.com/StatCan/aaw-kubeflow-containers/issues/310
Adds dos2unix

chore(package): add dos2unix

---

.github/workflows/build_push.yaml

Update actions/setup-python@v2 to actions/setup-python@v4
closes #486

Update build_push.yaml: actions/setup-python@v4

---

docker-bits/0_cpu.Dockerfile
docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/remote-desktop/firefox.sh
output/remote-desktop/remote-desktop/vs-code-desktop.sh
output/rstudio/Dockerfile
output/sas/Dockerfile
scripts/remote-desktop/firefox.sh
scripts/remote-desktop/vs-code-desktop.sh

May need to check / verify if extensions are working

chore(updates)

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

fix(cve): force babel/traverse installation

---

docker-bits/2_cpu.Dockerfile
docker-bits/7_remove_vulnerabilities.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Closes https://github.com/StatCan/aaw-private/issues/151

Update version of pyarrow

---

docker-bits/6_remote-desktop.Dockerfile
docker-bits/7_remove_vulnerabilities.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

closes https://github.com/StatCan/aaw-private/issues/155

fix(crypto): bump version

---

docker-bits/6_jupyterlab.Dockerfile
output/docker-stacks-datascience-notebook/start-oms.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/start-oms.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/start-oms.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/start-oms.sh
output/remote-desktop/start-oms.sh
output/rstudio/start-oms.sh
output/sas/Dockerfile
output/sas/start-oms.sh
resources/common/start-oms.sh

Adding the MPI Lib files required to build MPI models on aaw notebooks.

feat(Microsim): add MPI compiler libs

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/desktop-files/openmpp.desktop
output/sas/Dockerfile
resources/remote-desktop/desktop-files/openmpp.desktop

Bump the version of OMPP, change to MPI

feat(ompp_mpi): change openm to mpi release

---

output/docker-stacks-datascience-notebook/jupyterlab-overrides.json
output/jupyterlab-cpu/jupyterlab-overrides.json
output/jupyterlab-pytorch/jupyterlab-overrides.json
output/jupyterlab-tensorflow/jupyterlab-overrides.json
output/remote-desktop/jupyterlab-overrides.json
output/rstudio/jupyterlab-overrides.json
output/sas/jupyterlab-overrides.json
resources/common/jupyterlab-overrides.json

update(theme): dark to light

---

.github/workflows/build_push.yaml
docker-bits/6_rstudio-server.Dockerfile
docker-bits/6_rstudio.Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Fix curl in RStudio caused by openssl version mismatch.

---

docker-bits/6_remote-desktop.Dockerfile
output/remote-desktop/Dockerfile

closes [#1950](https://github.com/StatCan/aaw/issues/1950)

chore(openm): update remote desktop openm release

---

docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_rstudio.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

fixes https://github.com/StatCan/aaw-private/issues/178

updated jupyter-server-proxy version

---

docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Add more font deps:
- libtiff-dev
- libfreetype-dev
- libfreetype6
https://jirab.statcan.ca/browse/BTIS-235

Bryan more font deps

---

docker-bits/4_CLI.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

chore(utility): add pass

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

fixes https://jirab.statcan.ca/browse/BTIS-329

updated parquet extension version

---

.github/workflows/build_push.yaml
Makefile
requirements-dev.txt

fix(test images): pin requests package

---

README.md
docker-bits/0_cpu.Dockerfile
docker-bits/0_cpu_sas.Dockerfile
docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_rstudio.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

for https://github.com/StatCan/aaw-private/issues/182

fix(images): updated jupyter-server-proxy version

---

README.md
docker-bits/0_cpu.Dockerfile
docker-bits/0_cpu_sas.Dockerfile
docker-bits/6_rstudio.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

for https://github.com/StatCan/aaw-private/issues/182

fix(images): update jupyter-server-proxy version

---

.github/workflows/build_push.yaml
docker-bits/4_CLI.Dockerfile
docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_sas.Dockerfile
output/docker-stacks-datascience-notebook/start-oms.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/start-oms.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/start-oms.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/start-oms.sh
output/remote-desktop/Dockerfile
output/remote-desktop/start-oms.sh
output/rstudio/Dockerfile
output/rstudio/start-oms.sh
output/sas/Dockerfile
output/sas/start-oms.sh
resources/common/start-oms.sh

Update quarto version, move to all images

---

docker-bits/6_jupyterlab.Dockerfile
output/docker-stacks-datascience-notebook/start-oms.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/start-oms.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/start-oms.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/start-oms.sh
output/remote-desktop/start-oms.sh
output/rstudio/start-oms.sh
output/sas/Dockerfile
output/sas/start-oms.sh
resources/common/start-oms.sh

chore: update openm++ version and config

---

.github/workflows/build_push.yaml
docker-bits/6_sas.Dockerfile
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/Dockerfile
output/sas/SWE.folderShortcuts.key
output/sas/start-custom.sh
resources/common/start-custom.sh
resources/sas/SWE.folderShortcuts.key

fixes https://jirab.statcan.ca/browse/BTIS-381

feat(sas):add default file shortcut

---

docker-bits/4_CLI.Dockerfile
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/Dockerfile
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/Dockerfile
output/remote-desktop/start-custom.sh
output/rstudio/Dockerfile
output/rstudio/start-custom.sh
output/sas/Dockerfile
output/sas/start-custom.sh
resources/common/start-custom.sh

for https://jirab.statcan.ca/browse/BTIS-368

added new git cred manager args

---

docker-bits/0_Rocker.Dockerfile
docker-bits/6_rstudio.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile

Remove all shiny refs
Ticket: https://jirab.statcan.ca/browse/BTIS-426

Remove all shiny references

---

.github/workflows/build_push.yaml
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

for https://jirab.statcan.ca/browse/BTIS-496

added conditions in start custom script

---

docker-bits/6_jupyterlab.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/sas/Dockerfile

chore(add code-marketplace url): default to prod

---

.gitignore
Makefile

Fixes the issue with using `make build/%` locally.

add conditional local variable GITHUB_OUTPUT

---

docker-bits/4_CLI.Dockerfile
docker-bits/6_jupyterlab.Dockerfile
docker-bits/6_sas.Dockerfile
output/jupyterlab-cpu/Dockerfile
output/jupyterlab-pytorch/Dockerfile
output/jupyterlab-tensorflow/Dockerfile
output/remote-desktop/Dockerfile
output/rstudio/Dockerfile
output/sas/Dockerfile
scripts/CHECKSUMS

Fixes some newly discovered vulnerabilities from updating Trivy, 
closes https://github.com/StatCan/aaw-kubeflow-containers/issues/695

Fix vulnerabilities 2.0

---

output/docker-stacks-datascience-notebook/connect-to-filer.md
output/jupyterlab-cpu/connect-to-filer.md
output/jupyterlab-pytorch/connect-to-filer.md
output/jupyterlab-tensorflow/connect-to-filer.md
output/remote-desktop/connect-to-filer.md
output/rstudio/connect-to-filer.md
output/sas/connect-to-filer.md
resources/common/connect-to-filer.md

https://jirab.statcan.ca/browse/BTIS-549

chore(filer connection docs): update

---

Makefile
README.md

Add Table of Contents
Add instructions for generating dockerfiles to dev instructions
formatted white space
Add semantic line breaks
Update structure diagram

Improve readme

---

output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

for https://jirab.statcan.ca/browse/BTIS-680

feat: added curl command to get tnsnames.ora snippet value

---

.github/workflows/build_push.yaml
output/docker-stacks-datascience-notebook/start-custom.sh
output/jupyterlab-cpu/start-custom.sh
output/jupyterlab-pytorch/start-custom.sh
output/jupyterlab-tensorflow/start-custom.sh
output/remote-desktop/start-custom.sh
output/rstudio/start-custom.sh
output/sas/start-custom.sh
resources/common/start-custom.sh

fix: tnsnames curl networking issue
